// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ordering.proto

package ordering

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ordering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ordering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_ordering_proto protoreflect.FileDescriptor

const file_ordering_proto_rawDesc = "" +
	"\n" +
	"\x0eordering.proto\x12\bordering\"(\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"%\n" +
	"\bResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId2?\n" +
	"\bOrdering\x123\n" +
	"\n" +
	"PlaceOrder\x12\x11.ordering.Request\x1a\x12.ordering.ResponseB\fZ\n" +
	"./orderingb\x06proto3"

var (
	file_ordering_proto_rawDescOnce sync.Once
	file_ordering_proto_rawDescData []byte
)

func file_ordering_proto_rawDescGZIP() []byte {
	file_ordering_proto_rawDescOnce.Do(func() {
		file_ordering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordering_proto_rawDesc), len(file_ordering_proto_rawDesc)))
	})
	return file_ordering_proto_rawDescData
}

var file_ordering_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ordering_proto_goTypes = []any{
	(*Request)(nil),  // 0: ordering.Request
	(*Response)(nil), // 1: ordering.Response
}
var file_ordering_proto_depIdxs = []int32{
	0, // 0: ordering.Ordering.PlaceOrder:input_type -> ordering.Request
	1, // 1: ordering.Ordering.PlaceOrder:output_type -> ordering.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ordering_proto_init() }
func file_ordering_proto_init() {
	if File_ordering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordering_proto_rawDesc), len(file_ordering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordering_proto_goTypes,
		DependencyIndexes: file_ordering_proto_depIdxs,
		MessageInfos:      file_ordering_proto_msgTypes,
	}.Build()
	File_ordering_proto = out.File
	file_ordering_proto_goTypes = nil
	file_ordering_proto_depIdxs = nil
}
