// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ordering.proto

package server

import (
	"context"

	"ordering/rpc/internal/logic"
	"ordering/rpc/internal/svc"
	"ordering/rpc/ordering"
)

type OrderingServer struct {
	svcCtx *svc.ServiceContext
	ordering.UnimplementedOrderingServer
}

func NewOrderingServer(svcCtx *svc.ServiceContext) *OrderingServer {
	return &OrderingServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderingServer) PlaceOrder(ctx context.Context, in *ordering.Request) (*ordering.Response, error) {
	l := logic.NewPlaceOrderLogic(ctx, s.svcCtx)
	return l.PlaceOrder(in)
}
