// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ordering.proto

package orderingclient

import (
	"context"

	"ordering/rpc/ordering"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = ordering.Request
	Response = ordering.Response

	Ordering interface {
		PlaceOrder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultOrdering struct {
		cli zrpc.Client
	}
)

func NewOrdering(cli zrpc.Client) Ordering {
	return &defaultOrdering{
		cli: cli,
	}
}

func (m *defaultOrdering) PlaceOrder(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := ordering.NewOrderingClient(m.cli.Conn())
	return client.PlaceOrder(ctx, in, opts...)
}
